import React, { useState } from 'react';
import { Zap, Utensils, Brain, ThumbsUp, ThumbsDown } from 'lucide-react';
import { mockAiPlans } from '../data/mockData';
import Card from '../components/ui/Card';

const MyPlansPage = () => {
  const [activeTab, setActiveTab] = useState('fitness');
  const tabs = [
    { id: 'fitness', label: 'Fitness', icon: Zap },
    { id: 'nutrition', label: 'Nutrition', icon: Utensils },
    { id: 'mindfulness', label: 'Mindfulness', icon: Brain },
  ];

  const [completedWorkouts, setCompletedWorkouts] = useState([]); // Stores completed workout 'day'
  const [mealFeedback, setMealFeedback] = useState({}); // Stores feedback like { Breakfast: 'like' }

  const handleWorkoutToggle = (day) => {
    setCompletedWorkouts(prev => 
      prev.includes(day)
        ? prev.filter(item => item !== day) // Remove if already complete
        : [...prev, day] // Add if not complete
    );
    // In a real app, you might send this to the backend
  };

  const handleMealFeedback = (meal, feedback) => {
    setMealFeedback(prev => ({
      ...prev,
      [meal]: prev[meal] === feedback ? null : feedback // Toggle feedback
    }));
    // API Call: POST /api/recommendations/feedback (Section 3.3)
    console.log(`Feedback for ${meal}: ${feedback}`);
    // You'd show a "Feedback sent!" toast/message here
  };

  return (
    <div className="space-y-6">
      <h1 className="text-3xl font-bold text-gray-900">My AI-Driven Plans</h1>
      <p className="text-gray-600">
        Here are your personalized plans generated by our AI, based on your
        goals and biometric data.
      </p>
      
      {/* TODO: Add useEffect to fetch plans from /api/recommendations/... (Section 3.3) */}
      <Card>
        <div className="border-b border-gray-200">
          <nav className="-mb-px flex space-x-8" aria-label="Tabs">
            {tabs.map((tab) => (
              <button key={tab.id} onClick={() => setActiveTab(tab.id)}
                className={`whitespace-nowrap border-b-2 py-4 px-1 text-sm font-medium ${
                  activeTab === tab.id ? 'border-green-500 text-green-600' : 'border-transparent text-gray-500 hover:border-gray-300 hover:text-gray-700'
                }`}>
                <tab.icon className="inline-block h-5 w-5 mr-2" />{tab.label}
              </button>
            ))}
          </nav>
        </div>
        <div className="pt-6">
          {/* Fitness Tab */}
          {activeTab === 'fitness' && (
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold">{mockAiPlans.fitness.title}</h2>
              <p className="text-gray-600">{mockAiPlans.fitness.summary}</p>
              
              <div className="space-y-3">
                {mockAiPlans.fitness.schedule.map((item) => {
                  const isComplete = completedWorkouts.includes(item.day);
                  return (
                    <label 
                      key={item.day}
                      className={`flex items-center p-4 rounded-lg cursor-pointer ${
                        isComplete ? 'bg-green-50' : 'bg-gray-50 hover:bg-gray-100'
                      }`}
                    >
                      <input
                        type="checkbox"
                        className="h-5 w-5 rounded border-gray-300 text-green-600 focus:ring-green-500"
                        checked={isComplete}
                        onChange={() => handleWorkoutToggle(item.day)}
                      />
                      <span className={`ml-3 text-sm ${
                        isComplete ? 'line-through text-gray-500' : 'text-gray-900'
                      }`}>
                        <span className="font-semibold">{item.day}:</span> {item.workout} ({item.focus})
                      </span>
                    </label>
                  );
                })}
              </div>
            </div>
          )}
          {/* Nutrition Tab */}
          {activeTab === 'nutrition' && (
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold">{mockAiPlans.nutrition.title}</h2>
              <p className="text-gray-600">{mockAiPlans.nutrition.summary}</p>
              
              <div className="space-y-2">
                {mockAiPlans.nutrition.schedule.map((item) => {
                  const feedback = mealFeedback[item.meal];
                  return (
                    <div 
                      key={item.meal}
                      className="flex items-center justify-between p-4 bg-gray-50 rounded-lg"
                    >
                      <span className="text-sm text-gray-900">
                        <span className="font-semibold">{item.meal}:</span> {item.food}
                      </span>
                      {/* Feedback Buttons */}
                      <div className="flex space-x-2">
                        <button 
                          onClick={() => handleMealFeedback(item.meal, 'like')}
                          className={`p-2 rounded-full ${
                            feedback === 'like' ? 'bg-green-100 text-green-600' : 'text-gray-400 hover:bg-gray-200 hover:text-green-600'
                          }`}
                        >
                          <ThumbsUp className="h-5 w-5" />
                        </button>
                        <button
                          onClick={() => handleMealFeedback(item.meal, 'dislike')}
                          className={`p-2 rounded-full ${
                            feedback === 'dislike' ? 'bg-red-100 text-red-600' : 'text-gray-400 hover:bg-gray-200 hover:text-red-600'
                          }`}
                        >
                          <ThumbsDown className="h-5 w-5" />
                        </button>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          )}
          {/* Mindfulness Tab */}
          {activeTab === 'mindfulness' && (
            <div className="space-y-4">
              <h2 className="text-2xl font-semibold">{mockAiPlans.mindfulness.title}</h2>
              <p className="text-gray-600">{mockAiPlans.mindfulness.summary}</p>
              <ol className="list-decimal space-y-2 pl-5">
                {mockAiPlans.mindfulness.steps.map((item) => <li key={item.step}>{item.action}</li>)}
              </ol>
            </div>
          )}
        </div>
      </Card>
    </div>
  );
};

export default MyPlansPage;